# IMPORTING NECESSARY LIBRARIES

In [1]:
import numpy as np
import pandas as pd

# IMPORTING THE DATA

In [2]:
ps2=pd.read_excel("E:/ML/CONVOLVE/EPOCH-2/PS2/FileAndResults_Problem2.xlsx")
ps2

File Changed          Component     Coder       Tester  \
0             cpp/csyu/category/fnf    asr1001-flowpsk  Batukbaj        samsk   
1                    ignor-dp/build      asr1001-ignor      Alex  manishakang   
2                      ignor-dp/cdp      asr1001-ignor      Alex  manishakang   
3            ignor-dp/csco/affinity      asr1001-ignor      Alex  manishakang   
4                 ignor-dp/csco/cdp      asr1001-ignor      Alex  manishakang   
..                              ...                ...       ...          ...   
346                qkrvice/qk-infra                cgn      Alex  manishakang   
347            qkrvice/qk-infra-ipc             qk-cgn      Alex        samsk   
348                   qkrvice/qk-si                cgn      Alex  manishakang   
349           analyzedata/bmc-forge  asr1001-forge-cgn      Alex  manishakang   
350  analyzedata/forge-test-harness  asr1001-forge-cgn      Alex  manishakang   

        Category Sanity name nets Tested Sanity Result  
0     PD-asr1001  Thor_Vista     NCS5500          Pass  
1          Tools  vistra-cxr     NCS5500       Aborted  
2     PD-asr1001  vistra-cxr     NCS5500          Fail  
3     PD-asr1001  vistra-cxr     NCS5500       Aborted  
4     PD-asr1001  vistra-cxr     NCS5500       Aborted  
..           ...         ...         ...           ...  
346        PD-cm  vistra-cxr     NCS5500          Pass  
347        PD-cm  vistra-cxr     NCS5500          Fail  
348     PI-Infra  vistra-cxr     NCS5500          Pass  
349  analyzedata  vistra-cxr     NCS5500          Fail  
350  analyzedata  vistra-cxr     NCS5500          Fail  

[351 rows x 8 columns]

# APPLYING NLP TO 1ST COLUMN OF THE DATASET

In [3]:
# USING COUNT VECTORIZER
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
file_vect=vect.fit_transform(ps2["File Changed"])


In [4]:
data=ps2.copy()

# USING ONEHOTENCODER TO CONVERT CATEGORICAL FEATURES

In [5]:

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

x=data.drop(["File Changed","Sanity Result"],axis=1)

categorical_features=['Component', 'Coder', 'Tester', 'Category','Sanity name', 'nets Tested']
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",one_hot,categorical_features)])
transformed_x=transformer.fit_transform(x)
transformed_x

<351x121 sparse matrix of type '<class 'numpy.float64'>'
	with 2106 stored elements in Compressed Sparse Row format>

In [6]:
# USING LABEL ENCODING TO MAKE THE LABELS NUMERICAL
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(data["Sanity Result"])

In [7]:
# CONCATINATING VECTORS OF THE FIRST COLUMN (AFTER APPLYING NLP - COUNT VECTORIZER) WITH ONE HOT ENCODED DATA
# TO MAKE THE FINAL DATASET READY
transformed_x_df = pd.DataFrame(transformed_x.toarray())
file_vect_df = pd.DataFrame(file_vect.toarray())
d=pd.concat([transformed_x_df,file_vect_df],axis=1)
d

0    1    2    3    4    5    6    7    8    9    ...  126  127  128  \
0    0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...    0    0    0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...    0    0    0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...    0    0    0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...    0    0    0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...    0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
346  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0    0    0   
347  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0    0    0   
348  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0    0    0   
349  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...    0    0    0   
350  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...    0    0    0   

     129  130  131  132  133  134  135  
0      0    0    0    0    0    0    0  
1      0    0    0    0    0    0    0  
2      0    0    0    0    0    0    0  
3      0    0    0    0    0    0    0  
4      0    0    0    0    0    0    0  
..   ...  ...  ...  ...  ...  ...  ...  
346    0    0    0    0    0    0    0  
347    0    0    0    0    0    0    0  
348    0    0    0    0    0    0    0  
349    0    0    0    0    0    0    0  
350    0    0    1    0    0    0    0  

[351 rows x 257 columns]

# APPLYING MODEL ON FINALLY PROCESSED DATA

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# SETTING UP RANDOM SEED
np.random.seed(11)

#SPLITTING DATA INTO TRAIN AND TEST SET
xtrain,xtest,ytrain,ytest=train_test_split(d,y,test_size=0.2)

#THE MODEL
model=RandomForestClassifier()

#FITTING THE DATA
model.fit(xtrain,ytrain)



RandomForestClassifier()

In [9]:
# TESTING THE MODEL ON TEST SET
model.score(xtest,ytest)

0.9436619718309859

In [10]:
# USING CROSS_VAL_SCORE FOR BETTER ANALYSIS OF PERFORMANCE OF THE MODEL

from sklearn.model_selection import cross_val_score
cross_val_score(model,d,y,cv=5),np.mean(cross_val_score(model,d,y,cv=5))

(array([0.83098592, 0.9       , 0.8       , 1.        , 0.87142857]),
 0.8946881287726359)

In [11]:
# USING CLASSIFICATION REPORT FOR FURTHER ANALYSIS
from sklearn.metrics import classification_report
ypreds=model.predict(xtest)
rep=pd.DataFrame(classification_report(ytest,ypreds,output_dict=True))
rep

0     1          2  accuracy  macro avg  weighted avg
precision   1.0   0.8   0.959184  0.943662   0.919728      0.943662
recall      1.0   0.8   0.959184  0.943662   0.919728      0.943662
f1-score    1.0   0.8   0.959184  0.943662   0.919728      0.943662
support    12.0  10.0  49.000000  0.943662  71.000000     71.000000

In [12]:
# PRINTING THE CONFUSION METRICS
ypred=model.predict(xtest)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,ypred)
cm

array([[12,  0,  0],
       [ 0,  8,  2],
       [ 0,  2, 47]], dtype=int64)

In [13]:
# TUNING HYPERPARAMETERS FOR IMPROVING THE MODEL

#MAKING A GRID OF 
grid={
    "n_estimators":[50,125,175],
    "max_depth":[None,5,10],
    "max_features":["auto","sqrt"],
    "min_samples_split":[2,4],
    "min_samples_leaf":[1,2]
}

#USING GRIDSEARCHCV
from sklearn.model_selection import GridSearchCV
gs_clf=GridSearchCV(estimator=model,param_grid=grid,cv=5,verbose=2)
gs_clf.fit(transformed_x,y)

# GETTING THE BEST HYPERPARAMETERS
gs_clf.best_params_

Fitting 5 folds for each of 72 candidates, totalling 360 fits
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=   0.1s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=125; total time=   0.3s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_estimators=125; total time=   0.2s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=2, n_es

[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=125; total time=   0.3s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=125; total time=   0.3s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=125; total time=   0.2s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=None, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=None,

[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=125; total time=   0.2s
[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=125; total time=   0.2s
[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=125; total time=   0.2s
[CV] END max_depth=5, max_features=auto, min_samples_leaf=1, min_samples_split=4, n_estimators=125; total time=   0.2s
[CV] END max_depth=5, max_features=auto, min_samples

[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=1, min_samples_split=4, n_estimators=175; total time=   0.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=1, min_samples_split=4, n_estimators=175; total time=   0.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=1, min_samples_split=4, n_estimators=175; total time=   0.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=1, min_samples_split=4, n_estimators=175; total time=   0.3s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples

[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=125; total time=   0.2s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=125; total time=   0.2s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=125; total time=   0.3s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=125; total time=   0.3s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=125; total time=   0.2s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=10, max_features=auto, min_samples_leaf=2, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=10, max_features=auto

[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=2, n_estimators=175; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=4, n_estimators=50; total time=   0.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=4, n_estimators=50; total time=   0.0s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=4, n_estimators=125; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=2, min_samples_split=4, n_estimators=125; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min

{'max_depth': None,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 50}

In [14]:
np.random.seed(1)
model2=RandomForestClassifier(max_depth= None,
                                                 max_features= 'auto',
                                                 min_samples_leaf= 1,
                                                 min_samples_split= 2,
                                                 n_estimators= 50)
model2.fit(xtrain,ytrain) 
model2.score(xtest,ytest)

0.9436619718309859

In [15]:
# AS WE CAN SEE THERE IS NO IMPROVEMENT IN THE ACCURACY SCORE, HENSE OUR MODEL WAS TRAINED FOR THE BEST.....

In [16]:
# TAKING ANY RANDOM INPUT FROM THE DATASET
sample = ps2.iloc[7:17,:-1]
sample1 = ps2.iloc[7:17,:]
sample1

File Changed      Component     Coder       Tester  \
7   ignor-dp/csco/mb-netlink-repeater  asr1001-ignor      Alex          nel   
8                   ignor-dp/csco/ova  asr1001-ignor      Alex  manishakang   
9                 ignor-dp/csco/ports  asr1001-ignor      Alex  manishakang   
10              ignor-dp/csco/procman  asr1001-ignor   patrick  manishakang   
11                      ignor-dp/isod  asr1001-ignor   patrick  manishakang   
12                   ignor-dp/patches  asr1001-ignor   patrick  manishakang   
13                   ignor-dp/sixwind  asr1001-ignor   patrick  manishakang   
14   namespace/shsync/cfg/qkrvice-cgn         qk-cgn   patrick        samsk   
15           psrkp_ghfmeta/asr1001-li     asr1001-li  Batukbaj        samsk   
16        psrkp_ghfmeta/asr1001-li-64     asr1001-li  Batukbaj        samsk   

       Category Sanity name nets Tested Sanity Result  
7    PD-asr1001  vistra-cxr     NCS5500          Fail  
8    PD-asr1001  vistra-cxr     NCS5500          Pass  
9         Tools  vistra-cxr     NCS5500          Pass  
10   PD-asr1001  vistra-cxr     NCS5500          Pass  
11        Tools  vistra-cxr     NCS5500          Pass  
12   PD-asr1001  vistra-cxr     NCS5500          Pass  
13  analyzedata  vistra-cxr     NCS5500          Pass  
14     PI-Infra  vistra-cxr     NCS5500          Pass  
15   PD-asr1001  vistra-cxr     NCS5500          Pass  
16   PD-asr1001  vistra-exr     NCS5500          Pass

In [17]:
# CONVERTING THE DATA SLICE USING TRANSFORM

a = vect.transform(sample["File Changed"])
c = sample.drop("File Changed",axis=1)
b = transformer.transform(c)
e=pd.concat([pd.DataFrame(a.toarray()),pd.DataFrame(b.toarray())],axis=1)
e

0    1    2    3    4    5    6    7    8    9    ...  111  112  113  114  \
0    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
1    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
2    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
3    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
4    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
5    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
6    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
7    0    0    0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0  0.0   
8    0    0    0    0    0    0    1    0    0    0  ...  0.0  0.0  0.0  0.0   
9    1    0    0    0    0    0    1    0    0    0  ...  0.0  0.0  0.0  0.0   

   115  116  117  118  119  120  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  
5  0.0  0.0  0.0  0.0  0.0  0.0  
6  0.0  0.0  0.0  0.0  0.0  0.0  
7  0.0  0.0  0.0  0.0  0.0  0.0  
8  0.0  0.0  0.0  0.0  0.0  0.0  
9  0.0  0.0  0.0  0.0  0.0  0.0  

[10 rows x 257 columns]

In [18]:
# PREDICTIONG USING MODEL

pre=model.predict(e)
pre

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
le.inverse_transform(pre)

array(['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass'], dtype=object)

In [20]:
y

array([2, 0, 1, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0,
       0, 2, 2, 2, 0, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 1, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2,
       2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 1, 1, 2,
       0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 0, 0,
       2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 1, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [21]:
from sklearn.metrics import f1_score
f1_score(ytest,ypred,pos_label='positive',average='macro')

C:\Users\MITANSHU\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


0.9197278911564627

In [22]:
ypred

array([2, 2, 2, 1, 1, 2, 1, 1, 2, 0, 0, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1,
       0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 1, 0, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 2,
       2, 2, 2, 2, 2])